Repository Prophecy-eip/Maths, pull requests merged in 2022-05, with the labels that each got.

#30 chore(repo): Add a contributing file
  Cargo.toml
  Contributing.md
Labels: documentation

#32 add(architecture): build unit representaion
  src/single_units/unit.rs
Labels: PLD

#33 build(lib): Change wasm build to .so build to increase performances
  Cargo.toml
  Dockerfile
  build_lib.sh
  src/lib.rs
  src/single_units/unit.rs
Labels: enhancement
