Repository Prophecy-eip/Maths, pull requests merged in 2023-02, with the labels that each got.

#87 Ai/workspace fix
  src/ai/README.md
  src/ai/model.py
  src/ai/requirements.txt
  src/ai/utils.py
Labels: enhancement

#110 feat: Added a shots count (for the nb of attack) and a ballistic coun…
  src/ai/model.py
Labels: IA

#111 Hotfix/error response web server
  Cargo.toml
  src/dto/model.rs
  src/dto/modifier.rs
  src/main.rs
Labels: bug, enhancement, maths
